### ISSUE TITLE
Support split-exp for --multi flag

### ISSUE THREAD

**Issue by m-messiah** [CertainLach/jrsonnet#191]
The current `--multi` flag splits the document on its first level, so for example, yaml output:
```yaml
app:
   pod:
     name: my-pod
     appname: app
     image: app
   config:
     name: my-config
     data: "hello"
web:
  pod:
    name: web-pod
    appname: web
    image: nginx
  config:
     name: web-config
    data: "world"
```

when I use `jrsonnet --format yaml -c -m _output` it produces two files, that are hard to use later (they don't even have extension).
* `_output/app`
* `_output/web`

Both `yq` command allows split by the regex with something like `jrsonnet --format yaml | yq '.[].[]' -s '"_output/" + .appname + "/" + .name + ".yaml"'` to get the list of:
* _output/app/my-pod.yaml
* _output/app/my-config.yaml
* _output/web/web-pod.yaml
* _output/web/web-config.yaml

Do you think it would be possible to implement it in jrsonnet split multi instead of chaining with yq? (as far as I know, jq does not have this in box, making it even more difficult for json results)
